const ADD_DATA = 'ADD_DATA'
const ADD_ZVZS = 'ADD_ZVZS'
const OPEN_MODAL = 'OPEN_MODAL'
const CLOSE_MODAL = 'CLOSE_MODAL'
const ADD_PLAYER_TO_ZVZ = 'ADD_PLAYER_TO_ZVZ'
const INCREASE_COUNT = 'INCREASE_COUNT'
const DECREASE_COUNT = 'DECREASE_COUNT'
const REMOVE_ZVZ_PLAYER = 'REMOVE_ZVZ_PLAYER'
const CLEAR_ZVZ = 'CLEAR_ZVZ'

export default {
    ADD_DATA,
    ADD_ZVZS,
    OPEN_MODAL,
    CLOSE_MODAL,
    ADD_PLAYER_TO_ZVZ,
    INCREASE_COUNT,
    DECREASE_COUNT,
    REMOVE_ZVZ_PLAYER,
    CLEAR_ZVZ
}