const ADD_PLAYER = 'ADD_PLAYER'
const REMOVE_PLAYER = 'REMOVE_PLAYER'
const ADD_TOTAL_ZVZ = 'ADD_TOTAL_ZVZ'
const ADD_LAST_ZVZ = 'ADD_LAST_ZVZ'
const ADD_SUMMARY_ZVZS = 'ADD_SUMMARY_ZVZS'
const ADD_LAST_WEEKS_ZVZS = 'ADD_LAST_WEEKS_ZVZS'
const ADD_SUMMARY_BETWEEN_DATES= 'ADD_SUMMARY_BETWEEN_DATES'

export default {
    ADD_PLAYER,
    REMOVE_PLAYER,
    ADD_TOTAL_ZVZ,
    ADD_LAST_ZVZ,
    ADD_SUMMARY_ZVZS,
    ADD_LAST_WEEKS_ZVZS,
    ADD_SUMMARY_BETWEEN_DATES
}