const ADD_SET = 'ADD_SET'
const FETCH_SETS = 'FETCH_SETS'
const FETCH_ITEMS = 'FETCH_ITEMS'
const FETCH_DECLARATIONS = 'FETCH_DECLARATIONS'
const REMOVE_SET = 'REMOVE_SET'
const REMOVE_DECLARATION = 'REMOVE_DECLARATION'
const EDIT_SET = 'EDIT_SET'
const ADD_SHAME_LIST = 'ADD_SHAME_LIST'

export default {
    ADD_SET,
    FETCH_SETS,
    FETCH_ITEMS,
    FETCH_DECLARATIONS,
    REMOVE_SET,
    REMOVE_DECLARATION,
    EDIT_SET,
    ADD_SHAME_LIST
}